### ISSUE TITLE
The emoji are blurry on macOS and flicker as well

### ISSUE THREAD

**Issue by anosidium** [divadretlaw/EmojiText#21] opened 2024-01-25 16:47 UTC
EmojiText: 3.3.0
macOS: 14.2.1 (23C71)

Thank you for creating this Swift package. I am having issues using it on macOS as it renders the emoji blurry and I also see it flicker as well.

I tried using the `EmojiText` like this:

```Swift
EmojiText(verbatim: account.displayName, emojis: account.remoteEmoji)
     .font(.title)

EmojiText(markdown: account.displayName, emojis: account.remoteEmoji)
     .font(.title)

EmojiText(account.displayName, emojis: account.remoteEmoji)
     .font(.title)
```

The string value is:

```Swift
displayName = "George Takei :verified: 🏳️‍🌈🖖🏽"
```

How it looks on my app, Oliphaunt:

<img width="686" alt="image" src="https://github.com/divadretlaw/EmojiText/assets/39738481/057f6671-fab3-4d74-a0d9-81d16e64fe00">

Compared to how it looks on Safari:

![image](https://github.com/divadretlaw/EmojiText/assets/39738481/7a15a051-6070-459c-a452-56eb5b85e27e)

And the screen recording of the flicker:

https://github.com/divadretlaw/EmojiText/assets/39738481/d4dad820-464b-4079-89f0-8d7a3f167003

**Comment by divadretlaw** [comment] 2024-01-26 02:21
Hello, thank you for using the Swift Package and for opening an issue.

I released EmojiText `3.4.0` hopefully addressing your concerns (at least partially).

The blurry emoji were caused by not using the Retina display scale for calculating the target height of the emoji.

The emojis flicker because the placeholders are rendered first and only after the real emojis are loaded (from cache or remote) they will be rendered.
I think the main issue is that the text/layout is also moving, this was caused by the placeholder emoji not properly taking the baseline offset into account. So while the emoji can still switch from placeholder -> emoji, at least the rest of the text/layout shouldn't shift around anymore.

The default placeholder is `square.dashed` from SF Symbols. You can always provide a custom placeholder with

```swift
.placeholderEmoji(image: /* some UIImage or NSImage */)
```

Hopefully this will already improve the flicker issue, but I will see if that can be further improved for a future version.

**Comment by anosidium** [comment] 2024-01-26 18:25
EmojiText: 3.4.0
macOS: 14.2.1 (23C71)

Thank you for the quick improvements! I tried it again and I'm afraid that it still blurry and still flicker. Are there any other optimisations that I could try?

<img width="686" alt="image" src="https://github.com/divadretlaw/EmojiText/assets/39738481/309621d7-ecb2-4031-a0ac-1c6cdc8b90b2">

As for the flicker, since you are using Nuke Swift package, you could try adapting the implementation for `LazyImage` and `LazyImageView` because those views do not produce the flicker effect.

**Comment by divadretlaw** [comment] 2024-01-26 19:57
Hello, I noticed one issue. The emoji currently does not re-render when the display scale changes. e.g. moving it from a non-retina display to a retina display will result in a blurry emoji. This will be fixed in the next version.

Here some screenshots from a very simple Mastodon client, comparing `3.3.0` & `3.4.0`

| EmojiText | Retina Display | Non-Retina Display |
|:-:|:-:|:-:|
| `3.4.0` | <img width="488" alt="Screenshot 2024-01-26 at 16 39 47" src="https://github.com/divadretlaw/EmojiText/assets/6899256/584444f4-e6ff-4c2c-bfed-9999914c067a"> | ![Screenshot 2024-01-26 at 16 40 21](https://github.com/divadretlaw/EmojiText/assets/6899256/d9836eb9-e2e1-4dd2-ba3b-03ec335c0e60) |
| `3.3.0` | <img width="488" alt="Screenshot 2024-01-26 at 16 43 12" src="https://github.com/divadretlaw/EmojiText/assets/6899256/6f8be2b0-8c49-4ec7-905d-9bad6b59aaad"> | ![Screenshot 2024-01-26 at 16 40 21](https://github.com/divadretlaw/EmojiText/assets/6899256/d9836eb9-e2e1-4dd2-ba3b-03ec335c0e60) |

`LazyImage` or `LazyImageView` cannot be used unless they would somehow be usable with [LocalizedStringKey.StringInterpolation](https://developer.apple.com/documentation/swiftui/localizedstringkey/stringinterpolation)

**Comment by anosidium** [comment] 2024-01-26 20:25
I'm not changing my display resolution or anything like that.

Your retina screenshot for EmojiText version 3.4.0 looks sharp. How are you doing this? Why can't I achieve this on my app?

**Comment by divadretlaw** [comment] 2024-01-26 21:13
The view from the screenshots is now part of the TestApp on the `main` branch, maybe you can see something.

The `main` branch also contains some other minor improvements. I will look into the flicker issue some more, but currently I think its simply because there is a non-zero amount of time needed to load the emojis, even from cache, and in the meantime a placeholder is displayed.

If you have the time and can check if the `main` branch solves / improves any of your mentioned issues I would be grateful ☺️

**Comment by anosidium** [comment] 2024-01-27 18:29
Thank you for looking into this, David. I did check out the `main` branch and tested it. I wanted to give you some feedback and then I noticed that you updated the package to 3.5.0 and wanted to test it before reporting back to you and now I am having trouble. This is the issue reported from Xcode.

<img width="485" alt="image" src="https://github.com/divadretlaw/EmojiText/assets/39738481/afc22fb3-8d4d-4ec0-be48-d774d5803a12">

I tried resetting the package caches and resolving the versions and it didn't help.

**Comment by divadretlaw** [comment] 2024-01-27 18:42
Oh.. yeah I was storing the snapshots using Git LFS, but I guess that seems to have unintended consequences. I reverted that change and released `3.5.1` that should (hopefully) just work fine.

**Comment by anosidium** [comment] 2024-01-28 14:54
EmojiText: 3.5.1
macOS: 14.3 (23D56)

I tested the latest version and it looks significantly much better! Thank you very much for addressing this! Do you know if it is possible to make it work in a `String` like in the window title? I suppose some conversion to `NSAttributedString` using `NSTextAttachment` with `NSTextAttachmentCell`? Alternatively `NSTextAttachmentViewProvider` with `NSTextAttachmentLayout`.

<img width="686" alt="image" src="https://github.com/divadretlaw/EmojiText/assets/39738481/423da546-282c-46dd-80a4-01c46c7dbce0">

Unfortunately it still flicker, what I said earlier about `LazyImage`/`LazyImageView` is that not necessarily passing the `String` to it but using its implementation as in the business logic because those views do not produce the flicker effect. So adapt the business logic for `EmojiText`.

Is it possible to not have a placeholder at all, it shows nothing but occupy a space. Maybe that will resolve the flicker effect?

**Comment by divadretlaw** [comment] 2024-01-28 19:33
> Is it possible to not have a placeholder at all, it shows nothing but occupy a space. Maybe that will resolve the flicker effect?



```swift
.placeholderEmoji(image: /* some UIImage or NSImage */)
```

**Comment by divadretlaw** [comment] 2024-01-28 19:57
> Do you know if it is possible to make it work in a String like in the window title?

Currently no. A common iOS workaround is

```swift
.toolbar {
    ToolbarItem(placement: .principal) {
        EmojiText(verbatim: "Title :my_emoji:",
                  emojis: [RemoteEmoji(shortcode: "my_emoji", url: /* URL to emoji */)])
    }
}
```

But I don't think that applies to macOS.

In theory it would be possible to create a SwiftUI View Extension like `func navigationTitle(_ text: EmojiText) -> some View)` but that will require some re-organization of the code.

> what I said earlier about `LazyImage`/`LazyImageView` is that not necessarily passing the `String` to it but using its implementation as in the business logic because those views do not produce the flicker effect. So adapt the business logic for `EmojiText`.

Oh I see. I will look into that. Thank you for that suggestion. Possibly/Probably there is a way to quickly access the cache

> Is it possible to not have a placeholder at all, it shows nothing but occupy a space. Maybe that will resolve the flicker effect?

Yes, you can set your own placeholder via

```swift
.placeholderEmoji(image: /* some UIImage or NSImage */)
```

Simply set it to an empty image, then it will show nothing and occupy the space.

**Comment by divadretlaw** [comment] 2024-01-29 14:10
Hi, `3.5.2` should reduce the flicker

**Comment by divadretlaw** [comment] 2024-01-29 14:24
> Do you know if it is possible to make it work in a String like in the window title?

I tried to just set the generated `Text` in the title, but it doesn't work, because the title cannot be set to styled `Text` unfortunately. I get the following runtime error.

```
Only unstyled text can be used with navigationTitle(_:)
```

**Closed by divadretlaw** 2024-01-29 14:24 UTC
